### PR TITLE
Fixing issue where cartridge framework is null to resolve #112

### LINKED ISSUE #112: Handling of null framework in display of application images
The display of application images on the application list page is currently based off of the framework of the standalone cartridge. There is a possibility (especially for community based cartridges) for the framework to be null. This causes the page to fail to render due to a undefined resource.

### PR DESCRIPTION
**Pull request by sabre1041**
Resolves null pointer when displaying application image when cartridge framework is null

### CODE REVIEW

File: www/js/osm-operations.js [hunk 1]
```diff
@@ -240,9 +240,10 @@ function application_list_build(event) {
 		function inject(list,applications,index) {
 			var application = applications[index];
 			var li = $('<li id="aid-' + application.id + '"></li>');
+			var app_img_name = application.framework !== null && application.framework !== undefined ? application.framework.split('-')[0] : "default";
```
Comment (jyore) [inline www/js/osm-operations.js]: let's put `application.framework !== null && application.framework !== undefined` in parenthesis for readability sake. Other than that, it looks good

**Comment by sabre1041** [comment]
Parenthesis have been added as per PR comment
